### PR TITLE
Add support for V4 multipath

### PR DESCRIPTION
**Pull request by Nieuwejaar**

### CODE REVIEW

**Comment by rcgoodfellow** [comment]
Has this been tested in the omicron development environment setting?

**Comment by Nieuwejaar** [comment]
> Has this been tested in the omicron development environment setting?

I haven't done that explicitly.  I assumed that happened as part of omicron CI?

**Comment by rcgoodfellow** [comment]
Omicron CI will pick up the latest sidecar-lite CI artifacts from main.  In order to test a specific sidecar-lite branch you can use the `--softnpu-branch` argument [here](https://github.com/oxidecomputer/omicron/blob/main/tools/create_virtual_hardware.sh#L58-L61)

**Comment by Nieuwejaar** [comment]
> Omicron CI will pick up the latest sidecar-lite CI artifacts from main. In order to test a specific sidecar-lite branch you can use the `--softnpu-branch` argument [here](https://github.com/oxidecomputer/omicron/blob/main/tools/create_virtual_hardware.sh#L58-L61)

Yes, I've done that.

**Review by rcgoodfellow — APPROVED** [review]

**Pull request merged**
